docs: 添加线性代数与微积分部分
yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC pull request #68
Opened 2024-08-22 15:59 UTC by V1CeVersaa

2024-08-22 16:23 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    假设 $(X,d_X)$ 和 $(Y, d_Y)$ 是两个距离空间，$f: X\to Y$ 是这两个距离空间的映射. 假设 $x_0\in X$，$y_0 = f(x_0)\in Y$. 如果对于任意的 $\varepsilon>0$，都存在 $\delta>0$ 使得对于任意满足 $d_X(x, x_0) < \delta$ 的 $x\in X$，都有 $d_Y(f(x), y_0)
距离空间 -> 度量空间，两处

2024-08-22 16:24 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +在实数域上，倘若我们定义了一系列范数，比如 $p$ 范数，可以举出例子表明同一序列在不同范数下可能收敛到不同的极限，我们在习题中将涉及到这一点. 但是在有限维赋范线性空间上，这样的奇怪现象并不会出现，成为这个理论的基础是下面的 Weierstrass 定理：
更规范的说法是，$\ell_p$ 范数

2024-08-22 16:24 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +在实数域上，倘若我们定义了一系列范数，比如 $p$ 范数，可以举出例子表明同一序列在不同范数下可能收敛到不同的极限，我们在习题中将涉及到这一点. 但是在有限维赋范线性空间上，这样的奇怪现象并不会出现，成为这个理论的基础是下面的 Weierstrass 定理：
最后一句话，去掉“成为”

2024-08-22 16:27 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +在实数域上，倘若我们定义了一系列范数，比如 $p$ 范数，可以举出例子表明同一序列在不同范数下可能收敛到不同的极限，我们在习题中将涉及到这一点. 但是在有限维赋范线性空间上，这样的奇怪现象并不会出现，成为这个理论的基础是下面的 Weierstrass 定理：
等会，这句话意味不明，实数域不就是有限维赋范线性空间？这里的问题是，实数域不是紧的，所以不能对其应用 S-W 定理

2024-08-22 16:31 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +在实数域上，倘若我们定义了一系列范数，比如 $p$ 范数，可以举出例子表明同一序列在不同范数下可能收敛到不同的极限，我们在习题中将涉及到这一点. 但是在有限维赋范线性空间上，这样的奇怪现象并不会出现，成为这个理论的基础是下面的 Weierstrass 定理：
不是，实数域上也不可能出现这个情况，这只出现在无穷维

2024-08-22 16:34 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +在实数域上，倘若我们定义了一系列范数，比如 $p$ 范数，可以举出例子表明同一序列在不同范数下可能收敛到不同的极限，我们在习题中将涉及到这一点. 但是在有限维赋范线性空间上，这样的奇怪现象并不会出现，成为这个理论的基础是下面的 Weierstrass 定理：
这里的问题在于，有限维线性空间中的所有范数都是等价的，和 Weierstrass 没关系，请改正

2024-08-22 16:36 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +满足正定性、其次性与连续性的有限维实的或者复的向量空间上的实值函数被称为\term{准范数}，最经典的准范数当然是范数，上面这个定理告诉我们：在有限维实或者复的赋范线性空间上，所有的准范数都相差有限倍. 下面我们证明一下这个定理：
齐次性

2024-08-22 16:37 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    因为对每个非零的 $z\in\mathbf{F}^m$ 都有 $z/\Vert z\Vert_2\in S$，根据其次性得知 \[f_i(x(\frac{z}{\Vert z\Vert_2})) = f_i(\frac{1}{\Vert z\Vert_2}x(z)) = \frac{1}{\Vert z\Vert_2}f_i(x(z)),\]
齐次性

2024-08-22 16:38 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    该式对 $z = 0$ 也成立，因为 $f_1(0) = f_2(0) = 0$，每一个 $v\in V$ 都可以表示成 $\mathcal{B}$ 的线性组合的形式，所以自然可以表示成 $v = x(z)$ 的形式，这样孑军中的不等式对所有的 $x\in V$ 都成立.
孑军是什么东西

2024-08-22 16:40 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +证明非常简单，直接略过则可. 在实或者复向量空间上，如果两个范数关于同一列向量序列的收敛性是等价的，那么这两个范数是\term{等价}的. 上面的论述告诉我们：\term{有限维实或者复向量空间上的范数都是等价的}，这就是我们在有限维赋范线性空间上研究范数的一个重要结论. 无限维线性空间上的结论就要复杂得多，读者可以阅读有关矩阵分析的书籍来了解更多.
一个不太难表明的结果是，总存在两个不等价的范数，可以补一下证明

2024-08-22 16:41 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    设 $A$ 是赋范线性空间 $X$ 到赋范线性空间 $Y$ 上的线性映射，假设 $A$ 在某一点 $x_0\in X$ 处连续，那么 $A$ 是 $X$ 上的连续映射.
这里可以补充一个评述：这体现了线性算子和一般的函数之间的显著差异。线性性能够将一个局部的性质放大到整体的性质，这是这个证明的精髓。

2024-08-22 16:43 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    从赋范线性空间 $X$ 到赋范线性空间 $Y$ 上的线性映射 $A$ 是有界映射的充分必要条件是 $A$ 是连续映射.
这通常被称为 bounded linear transformation theorem, BLT 定理（闭线性变换定理）

2024-08-22 16:46 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +前半段很简单，若 $A$ 为不可逆矩阵，那么 $\det A = 0$，取出 $A$ 的每个元素 $a_i$，$(1\leqslant i\leqslant n^2)$，将 $a_i$ 视为 $\mathbf{R}$ 上的一个变量，那么 $\det A$ 就是关于 $a_i$ 的一个多项式，这个多项式的零点对应的元素形成的矩阵构成的集合就是不可逆矩阵的集合，显然是零测的. 对于后半段，我们证明这
说明：为什么全体多项式的零点集是零测的

2024-08-22 16:48 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    对函数 $f: \mathbf{R}^n\to \mathbf{R}$，设 $f$ 在 $x_0$ 处可微，那么 $f$ 在 $x_0$ 处的方向导数都存在，并且有\[\frac{\partial f}{\partial u}(x_0) = \mathrm{d}f(x_0)(u).\]
可微的定义没写

2024-08-22 16:49 UTC, V1CeVersaa commented on 讲义/专题/25 线性代数与微积分.tex
> +前半段很简单，若 $A$ 为不可逆矩阵，那么 $\det A = 0$，取出 $A$ 的每个元素 $a_i$，$(1\leqslant i\leqslant n^2)$，将 $a_i$ 视为 $\mathbf{R}$ 上的一个变量，那么 $\det A$ 就是关于 $a_i$ 的一个多项式，这个多项式的零点对应的元素形成的矩阵构成的集合就是不可逆矩阵的集合，显然是零测的. 对于后半段，我们证明这
指出构成一个超曲面就可以嘛

2024-08-22 16:50 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +\end{theorem}
可以画成立体的图

2024-08-22 16:52 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +拟微分中值定理告诉我们，雅各布矩阵的范数可以用来估计向量值函数的改变量. 下面的结果给出了向量值函数与其线性化映射之间的误差估计.
Jacobi 矩阵，中英文术语统一

2024-08-22 16:52 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +对于恒同映射 $I_n$ 来讲，范数小于 $1$ 的映射相对于它是一个\textrm{微小扰动}，上面的例子告诉我们，对于一个像恒同映射这样的可逆映射施加一个微小扰动得到的映射是可逆的. 在一般的向量值函数中，微小扰动的例子丰富极了，因为每一个在某一点 $x_0$ 可微的向量值函数在该点都可以将其线性化，也就是分解成 $L(x - x_0) + o(\Vert x - x_0\Vert)$，将后
term

2024-08-22 16:53 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +这个例子可以很轻松地推广到一般形式，只需要将偏导数换成雅各布矩阵，这就是隐函数定理的内容. 但在正式介绍隐函数定理之前，我们看一下它线性的说法：
Jacobi

2024-08-22 16:53 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    对于一个线性空间 $X$ 上的线性变换 $P\in \mathcal{L}(X)$ 满足 $P^2 = P$，那么称 $P$ 为 $X$ 里的一个\term{射影}. 射影满足下面的性质：
这里的术语确定一下，个人认为投影比较好

2024-08-22 16:54 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +现在我们要考虑比线性映射更一般的映射，根据“连续可微映射在某一点的局部性质与其在该点的微分的性质相同”这一核心原理，我们可以猜测对于某一点 $P$，如果 $\det J\varphi(P)\neq 0$，对于 $P$ 附近的一个非常小的可求体积的图形 $A$，有 $\nu(\varphi(A)) = \vert\det J\varphi(P)\vert \nu(A)$. 对这样的一个个小的面积元
注意引号

2024-08-22 17:00 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +设 $D\subset \mathbf{R}^n$ 为开集，$\varphi: D\to \mathbf{R}^n$ 为 $C^1$ 映射，根据拟微分中值定理，我们可以知道 $\varphi$ 是一个局部 Lipschitz 映射，也就是任取一个闭集 $P\subset D$ 与点 $x, y\in P$，存在 $\rho > 0$ 使得 \[\vert \varphi(x) - \varphi
局部 Lipschitz 的定义是错的，这个就叫 Lipschitz，也不需要任取一个闭集这个废话

2024-08-22 17:00 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +所以下面讨论的主题就是如何对可求体积的集合 $A$ 在这样一个局部 Lipschitz 映射下的像 $\varphi(A)$ 的体积进行估计.
删掉局部

2024-08-22 17:02 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    根据反函数定理，$\varphi:D\to \varphi(D)$ 是可逆的，所以我们对于 $\varphi^{-1}$ 与 $\displaystyle\int_{A}f\circ\varphi\vert\det J\varphi\vert$ 进行类似的论证，可以得到 \[\int_{A}f \circ \varphi\vert \det J\varphi\vert \leqslant
你到底要不要 \displaystyle？

2024-08-22 17:06 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +设 $D\subset \mathbf{R}^n$ 为开集，$\varphi: D\to \mathbf{R}^n$ 为 $C^1$ 映射，根据拟微分中值定理，我们可以知道 $\varphi$ 是一个局部 Lipschitz 映射，也就是任取一个闭集 $P\subset D$ 与点 $x, y\in P$，存在 $\rho > 0$ 使得 \[\vert \varphi(x) - \varphi
局部 Lipschitz 的定义应该是：对于任意一点 $x$，存在一个开邻域 $U$ 和常数 $L$ 使得任意 $f|_U$ 是 $L$-Lipschitz 的

2024-08-22 17:06 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +所以下面讨论的主题就是如何对可求体积的集合 $A$ 在这样一个局部 Lipschitz 映射下的像 $\varphi(A)$ 的体积进行估计.
或者改写一下局部的定义也行

2024-08-22 17:08 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +设 $D\subset \mathbf{R}^n$ 为开集，$\varphi: D\to \mathbf{R}^n$ 为 $C^1$ 映射，根据拟微分中值定理，我们可以知道 $\varphi$ 是一个局部 Lipschitz 映射，也就是任取一个闭集 $P\subset D$ 与点 $x, y\in P$，存在 $\rho > 0$ 使得 \[\vert \varphi(x) - \varphi
对于全局 Lipschitz 的函数我们往往会有一些更加好的估计，这里应该还是写成局部比较好

2024-08-22 17:16 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +        \item $\Vert AB\Vert\leqslant\Vert A\Vert\Vert B\Vert$.
第四条性质被称为次可乘性（sub-multiplicative），矩阵范数不一定满足这个性质

2024-08-22 17:20 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    很容易可以验证其满足范数的四条性质.
比方说，当 $p$ 取到 $\infty$ 时，它就没有次可乘性。有次可乘性的范数有时被称为环范数（ring norm, c.f. Horn）

2024-08-22 17:24 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    设 $\Vert \cdot\Vert$ 是定义在域 $\mathbf{F}$ 的赋范向量空间 $V$ 上的一个范数，$F$ 可以为实数域或者复数域，$m\geqslant 1$ 是一个给定的正整数，$x^{(1)}, x^{(2)}, \dots, x^{(m)}\in V$ 是给定的向量组，又对任意的 $z = (z_1, \cdots, z_m)^T \in \mathbf{F}^
$\mathbf{F}$，以及你并未定义复数域上的范数，它要求把绝对值改成模长

2024-08-22 17:25 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    设 $f_1$ 和 $f_2$ 是域 $\mathbf{F}$ 上的一个有限维向量空间 $V$ 上的一个实值函数，这里的 $\mathbf{R}$ 可以是实数域或者是复数域，设 $\mathcal{B} = \{x^{(1)}, x^{(2)}, \dots, x^{(m)}\}$ 是 $V$ 的一个基，对 $z = (z_1, z_2, \dots, z_m)^T\in \mathbf
$\mathbf{R}$ 可以是实数域或者复数域是什么奇怪的记号

2024-08-22 17:27 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    因为对每个非零的 $z\in\mathbf{F}^m$ 都有 $z/\Vert z\Vert_2\in S$，根据其次性得知 \[f_i(x(\frac{z}{\Vert z\Vert_2})) = f_i(\frac{1}{\Vert z\Vert_2}x(z)) = \frac{1}{\Vert z\Vert_2}f_i(x(z)),\]
值得一提的是，为啥无限维不行？因为无限维里的单位球不是紧的，证明从略

2024-08-22 17:28 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    因为对每个非零的 $z\in\mathbf{F}^m$ 都有 $z/\Vert z\Vert_2\in S$，根据其次性得知 \[f_i(x(\frac{z}{\Vert z\Vert_2})) = f_i(\frac{1}{\Vert z\Vert_2}x(z)) = \frac{1}{\Vert z\Vert_2}f_i(x(z)),\]
第一个 $n$ 应该是 $m$

2024-08-22 17:30 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    设 $A$ 是赋范线性空间 $X$ 到赋范线性空间 $Y$ 的线性映射，如果存在常数 $M\leqslant 0$ 使得对于任意 $x\in X$，都有 \[\Vert Ax\Vert\leqslant M\Vert x\Vert,\]
应该是 $M \geqslant 0$，你无敌了

2024-08-22 17:34 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +\end{theorem}
等等，$Omega$ 是什么玩意？

2024-08-22 17:37 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    我们令 $\Omega = D$，$g = f^{-1}: \Omega\to\Delta$，那么有 $g \circ f = \mathrm{id}_{\Omega}$，根据链式法则有 \[\mathrm{Id}_{\Omega} = I_{n} = J(g\circ f)(x_0) = Jg(y_0)\cdot Jf(x_0),\]
不明意义的记号替换，以及为啥 $g$ 是 $\Omega \to \Delta$，我猜你想记 $\Omega = f(D)$，然后 $g: \Omega \to D$

2024-08-22 17:37 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    根据线性代数的知识，很容易可以看出 $Jf(x)$ 和 $Jg(g)$ 都需要是一个方阵，这就是 (1). 并且也足以说明 $Jf(x)$ 是可逆的，也就是$Jg(y) = (Jf(x))^{-1}.$
应该是 $J g(y)$

2024-08-22 17:41 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +对于恒同映射 $I_n$ 来讲，范数小于 $1$ 的映射相对于它是一个\textrm{微小扰动}，上面的例子告诉我们，对于一个像恒同映射这样的可逆映射施加一个微小扰动得到的映射是可逆的. 在一般的向量值函数中，微小扰动的例子丰富极了，因为每一个在某一点 $x_0$ 可微的向量值函数在该点都可以将其线性化，也就是分解成 $L(x - x_0) + o(\Vert x - x_0\Vert)$，将后
什么叫 $k$ 次连续可微？应该叫 $k$ 次微分连续

2024-08-22 17:46 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    沿用上面的记号，则当 $B\subset A$ 可求体积且 $d(B) < \eta$ 时，有 \[\nu(\varphi(B)) \leqslant \left[\vert \det J\varphi(x)\vert + O(\varepsilon)\right]\nu(B),\enspace x\in B.\]
这里不要用方括号，用小括号

2024-08-22 17:48 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    通过 $B\subset B_\eta(x)$ 可以得到 $\nu(L\circ\varphi(B)) \leqslant (1 + C\varepsilon)^n\nu(B)$，所以\[\nu(\varphi(B)) = \frac{\nu(L\circ\varphi(B))}{\vert \det L\vert}\leqslant \vert \det J\varphi(x)\ver
同理，用小括号，公式最后漏了 $\nu(B)$

2024-08-22 17:49 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    不妨设 $A$ 为一个矩形，且 $f$ 非负，对于 $A$ 的任意一个分割 $\pi = \{A_{ij}\}$，我们有\[\int_{\varphi(A)}f = \sum_{i, j}\int_{\varphi(A_{ij})}f \leqslant \sum_{i, j}[\sup\limits_{\varphi(A_{ij})}f]\nu(\varphi(A_{ij})).\]
补充一句，这里的“不妨设”来源于第一覆盖引理以及可数可加性

2024-08-22 17:50 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    另 $\varepsilon\to0^+$ 可以得到\[\int_{\varphi(A)}f\leqslant \int_A f\circ\varphi\vert\det J\varphi\vert.\]
令

2024-08-22 17:51 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    另 $\varepsilon\to0^+$ 可以得到\[\int_{\varphi(A)}f\leqslant \int_A f\circ\varphi\vert\det J\varphi\vert.\]
这里不要用方括号

2024-08-22 17:57 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    我们对 $A\setminus \bigcup_iB_i^1$ 重复上述过程，可以得到包含于 $A\setminus \bigcup_iB_i^1$ 有限个小球体 $\{B_{i'}^2\}$ 使得 \[0 < \nu\left(A\setminus \bigcup_iB_i^1\setminus \bigcup_{i'}B_{i'}^2\right) < q\nu\left(A\set
这里一个提示是，为啥这个差集依然是可求体积的？因为它差掉了一个**有限**并

2024-08-22 17:57 UTC, 45gfg9 requested changes
图和间距，这部分等我自己 resolve

2024-08-22 17:57 UTC, 45gfg9 commented on 讲义/专题/25 线性代数与微积分.tex
> +    % TODO 图
TODO

2024-08-22 17:57 UTC, 45gfg9 commented on 讲义/专题/25 线性代数与微积分.tex
> +这个例子告诉我们：坐标变换允许我们将被积区域进行变换，比如将圆或球转化成一个矩形，这样就可以极大简化运算. 更确切来说，对于原被积区域 $\Omega$ 上的函数 $f$，我们可以定义一个映射 $\varphi\colon \Sigma \to \Omega,\enspace \varphi(\Sigma) = \Omega$，使得我们只需要在现被积区域 $\Sigma$ 对复合函数 $f\ci
TODO: spacing needs fix

2024-08-22 17:57 UTC, 45gfg9 commented on 讲义/专题/25 线性代数与微积分.tex
> +              % TODO 图
TODO

2024-08-22 17:57 UTC, 45gfg9 commented on 讲义/专题/25 线性代数与微积分.tex
> +              % TODO 图
TODO

2024-08-22 17:59 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    将这一部分不断重复下去，对于任意的 $\varepsilon > 0$，由于 $q^k\to 0\enspace (k\to \infty)$，所以当 $k$ 充分大的时候，我们就得到内部互不相交的一列 $n$ 维球体 $\{B_i\}$ 使得 \[0 < \nu\left(A\setminus \bigcup_iB_i\right) < q^k\nu(A) < n^{-n/2}\fra
一列？应该是一族，因为是有限个，如果是可数个就炸了

2024-08-22 17:59 UTC, 45gfg9 commented on 讲义/专题/25 线性代数与微积分.tex
> +反函数定理与隐函数定理对函数在 $(x^0, y^0)$ 时的微分 $J_*f(x^0, y^0)$ （这里的 $*$ 表示隐函数对 $y$ 求微分）有着很高的要求，亦即要求它是可逆也就是\term{满秩}的，那么如果这个微分不满秩呢？下面的\term{秩定理}. 我们还是先回忆一点关于线性变换的事实.
句子没写完

2024-08-22 18:03 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    定义从 $E$ 到 $\mathbf{R}^n$ 内的映射 $G$ 满足：\[G(x) = x + SP[f(x) - Ax], \enspace \forall x\in E.\]
用小括号

2024-08-22 18:05 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    令 $\Phi(x) = f(H(x))$，$x\in V$，因为对于每一个 $x\in V$，$JH(x)$ 的秩为 $n$，而对每个 $x\in U$，$Jf(x)$ 的秩为 $r$，所以 \[r(J\Phi(x)) = r(Jf(H(x))\cdot JH(x)) = r, \enspace \forall x \in V.\]
这里记号很乱，应该用 $\rank$

2024-08-22 18:08 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    因为 $Jf(x_0) = A$，对 $G$ 求微分则有 $JG(x_0) = I_n$，根据反函数定理，存在开集 $U$ 与 $V$，$x_0\in U$，$G$ 为将 $U$ 映满 $V$ 的连续可微一一映射，且 $G$ 的逆 $H$ 也是连续可微映射. 此外，我们还可以将 $U$ 与 $V$ 收缩一下，使 $V$ 成为凸集，这样 $JH(x)$ 就对于每个 $x\in V$ 可逆.
这句话很不明确，什么叫 $U$ 和 $V$ 收缩一下？直接说取 $V'$ 为含于 $V$ 的凸集，$U' = H(V')$ 就清楚了

2024-08-22 18:09 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    因为 $Jf(x_0) = A$，对 $G$ 求微分则有 $JG(x_0) = I_n$，根据反函数定理，存在开集 $U$ 与 $V$，$x_0\in U$，$G$ 为将 $U$ 映满 $V$ 的连续可微一一映射，且 $G$ 的逆 $H$ 也是连续可微映射. 此外，我们还可以将 $U$ 与 $V$ 收缩一下，使 $V$ 成为凸集，这样 $JH(x)$ 就对于每个 $x\in V$ 可逆.
当然，一个问题是，为啥总有这么一个凸集存在？这是因为 $U$ 是 $x$ 的一个开邻域，所以 $V$ 是 $G(x)$ 的一个开邻域，所以总存在一个 $G(x)$ 附近的开球含于 $V$，可以将其取成 $V'$

2024-08-22 18:10 UTC, 45gfg9 commented on 讲义/专题/25 线性代数与微积分.tex
> +    令 $\Phi(x) = f(H(x))$，$x\in V$，因为对于每一个 $x\in V$，$JH(x)$ 的秩为 $n$，而对每个 $x\in U$，$Jf(x)$ 的秩为 $r$，所以 \[r(J\Phi(x)) = r(Jf(H(x))\cdot JH(x)) = r, \enspace \forall x \in V.\]
🤔 正文里用的都是 $ r $

2024-08-22 18:11 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    固定 $y_0\in A(V)$，再固定 $x_0\in V$ 使得 $Ax_0 = y_0$，因为 $V$ 是开集，$y_0$ 必在 $Y_1$ 中有临域 $W$，对于任意的 $y\in W$，向量 $x = x_0 + S(y - y-0)$ 一定在 $V$ 中，所以 \[Ax = A(x_0) + y - y_0 = y.\]
邻域，$y_0$

2024-08-22 18:18 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    设 $Ah = 0$，那么 $PH\Phi(x)h = 0$，但是 $J\Phi(x)h \in M$，并且 $P$ 在 $M$ 上是一一映射，因此 $J\Phi(x)h = 0$，所以到这里我们已经证明了：若 $x\in V$，且 $Ah = 0$，那么 $J\psi(x)h = 0$，往回一步，我们证明对于 $x_1, x_2\in V$，$Ax_1 = Ax_2$，就有 $\psi
$P J\Phi(x) h$，不是 $P H \Phi(x) h$

2024-08-22 18:21 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +注意到，对于一般的线性空间 $X$，如果范数定义得当，就算是 $X$ 是无穷维的，我们对有限维线性空间上的线性映射定义的范数施用在无穷维线性空间上的线性映射也是有意义的，但我们敏锐的嗅觉告诉我们，一旦加上了“无穷维”这个不容易处理的条件，无穷维线性空间上的线性映射的性质就会变得更加复杂，我们暂且不对其继续深入讨论.
这里线性空间的记号用 $V$，不要用 $X$，容易混淆

2024-08-22 18:23 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    很容易可以验证其满足范数的四条性质.
更广泛的，可以定义 Schatten 范数，这里有一个 von Neumann 迹不等式的直接应用，可以留做习题

2024-08-22 18:40 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +满足正定性、其次性与连续性的有限维实的或者复的向量空间上的实值函数被称为\term{准范数}，最经典的准范数当然是范数，上面这个定理告诉我们：在有限维实或者复的赋范线性空间上，所有的准范数都相差有限倍. 下面我们证明一下这个定理：
准范数建议翻译为仿范数（paranorm），它的要求只有正性没有定性（下面也没用到定性）；需要与半范数（seminorm）和准范数/拟范数（quasinorm）区分。实际上一般的定义说法是满足某种连续性条件的、在拓扑群上的一个 $G$-半范数，当然，这里的连续性蕴含了次可加性。

2024-08-22 18:41 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +满足正定性、其次性与连续性的有限维实的或者复的向量空间上的实值函数被称为\term{准范数}，最经典的准范数当然是范数，上面这个定理告诉我们：在有限维实或者复的赋范线性空间上，所有的准范数都相差有限倍. 下面我们证明一下这个定理：
而且，这里你要求 $f_2$ 不需要连续性，所以不是准范数相差有限倍。为了防止问题，建议直接用范数代替

2024-08-22 18:52 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +满足正定性、其次性与连续性的有限维实的或者复的向量空间上的实值函数被称为\term{准范数}，最经典的准范数当然是范数，上面这个定理告诉我们：在有限维实或者复的赋范线性空间上，所有的准范数都相差有限倍. 下面我们证明一下这个定理：
思考了一下，或许直接用半范数更好。半范数在此时自然地具备连续性（从次可加性给出），并且半范数可以用来在两侧压一个范数，这是由 B-W 定理给出的。所以说连续性完全是不必要的，用次可加性直观的多。

2024-08-22 19:11 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +前半段很简单，若 $A$ 为不可逆矩阵，那么 $\det A = 0$，取出 $A$ 的每个元素 $a_i$，$(1\leqslant i\leqslant n^2)$，将 $a_i$ 视为 $\mathbf{R}$ 上的一个变量，那么 $\det A$ 就是关于 $a_i$ 的一个多项式，这个多项式的零点对应的元素形成的矩阵构成的集合就是不可逆矩阵的集合，显然是零测的. 对于后半段，我们证明这
比较麻烦的问题是，怎么表明一个超曲面在高维空间中零测，实际上你需要取出有限个总体积趋于 0 的开方体将其覆盖

2024-08-22 19:14 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    令 $\Phi(x) = f(H(x))$，$x\in V$，因为对于每一个 $x\in V$，$JH(x)$ 的秩为 $n$，而对每个 $x\in U$，$Jf(x)$ 的秩为 $r$，所以 \[r(J\Phi(x)) = r(Jf(H(x))\cdot JH(x)) = r, \enspace \forall x \in V.\]
但是这里同时有 r 表示秩和正整数 r，要不把正整数 r 改成正整数 p？

2024-08-23 02:23 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    那么就有 \[\mathrm{d}f(x_0)(u) = \nabla f(x_0)\cdot u.\]这就表明了\textbf{梯度其实是微分的矩阵表示}.
为啥是矩阵表示？更好的表述是不是应该说，是微分在标准正交基下的向量表示？

如果预设一些背景的话，也可以说实际上它就是在（余）切空间中、标准正交基诱导的坐标下的向量表示。

2024-08-23 02:24 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +既然函数就是两个集合之间的映射，迄今为止我们考虑的一直是$\mathbf{R}^n$上的实值函数，既然线性映射都可以是从$\mathbf{R}^n$到$\mathbf{R}^m$的，那么函数当然也可以这样，这就是\term{向量值函数}.
后面的既然改成而且

2024-08-23 02:26 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    设 $D\subset\mathbf{R}^n$ 是开集，$f\colon D\to\mathbf{R}^m$ 是一个向量值的多元函数函数，$x_0\in D$. 如果存在一个线性映射 $L\in \mathcal{L}(\mathbf{R}^n, \mathbf{R}^m)$ 使得在 $x_0$ 附近成立\[f(x) - f(x_0) = L(x-x_0) + o(\Vert x-x_
这个 $o$ 记号不太明确，可能写成极限的形式比较好

2024-08-23 02:29 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +从一元函数到多元函数，对微分的定义其实迈上了一个新的台阶，原因其实是自变量的每一个分量“杂糅”在一起，我们需要单独将每一个分量“拎出来”单独讨论，所以这就是偏导数与全微分的来源. 但是对于向量值函数而言，它的每一个分量并没有什么特别强的联系——这是因为我们有了坐标，并且这严重依赖于坐标系的选取——所以我们可以将从 $\mathbf{R}^n$ 到 $\mathbf{R}^m$ 的向量值函数拆成
某种意义上，偏导数就是“坐标”，而全微分就是“线性空间的基”

2024-08-23 02:36 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +所以这是一个压缩映射，因此 $\varphi$ 有唯一的不动点，即存在唯一的 $x_*\in \mathbf{R}^n$ 使得 $x_* = Ax_* + v$，即 $(I_n - A)x_* = v$，所以 $I_n - A$ 为单射，即可逆.
“所以这”讲明白

2024-08-23 02:39 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +对于恒同映射 $I_n$ 来讲，范数小于 $1$ 的映射相对于它是一个\term{微小扰动}，上面的例子告诉我们，对于一个像恒同映射这样的可逆映射施加一个微小扰动得到的映射是可逆的. 在一般的向量值函数中，微小扰动的例子丰富极了，因为每一个在某一点 $x_0$ 可微的向量值函数在该点都可以将其线性化，也就是分解成 $L(x - x_0) + o(\Vert x - x_0\Vert)$，将后一项
连续可微这个术语有点奇怪

continuously differentiable 可能更好的译法是“微分连续”，这里怎么表述更清楚可以讨论一下

当然，如果数分课本就这么叫那当我没说

2024-08-23 02:45 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +        \item $h \colon V\to U$ 是 $C^k$ 的：由 (2) 有 $Jh(y) = Jf(h(y))^{-1},\enspace \forall y\in V$. 由于 $f$ 是 $C^k$ 的知 $Jf$ 是 $C^{k-1}$ 的. 由上知 $Jh$ 连续，所以 $h$ 是 $C^2$ 的，以此类推就可得到 $h$ 是 $C^k$ 的.
这里的写法并不合适。$J h$ 连续应当只能表明 $h$ 是 $C^1$ 的，这里应该用链式法则写开一步会更加清楚

2024-08-23 02:53 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +    首先证明：对于 $x_1, x_2\in V$，$Ax_1 = Ax_2$，那么 \[\psi(x_1) = f(H(x_1)) - Ax_1 = f(H(x_2)) - Ax_2 = \psi(x_2).\]
第一步是，表明我们的 $\psi$ 是良定的，这也就是说要证明……

2024-08-23 02:57 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +              设 $A$ 为 $\mathbf{R}^n$ 中的可求体积的有界集合，则任给 $\varepsilon > 0$，存在有限个矩形 $\{I_i\}$ 与 $\{J_j\}$ 使得
对于“可求体积”，应该做一个评述：有限个可求体积的集合的并和交可求体积，但必须是有限个，这是很关键的一点

2024-08-23 03:00 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +              此时就有 \[\nu(A) < \sum_{I_{ij}\cap A\neq \varnothing}\nu(I_{ij}) < \nu(A) + \varepsilon.\]
这里最好显式地写一下 $I_i$ 和 $J_i$，实际上 $J_i$ 内部似乎也不会相交

2024-08-23 03:05 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +现在我们要考虑比线性映射更一般的映射，根据“连续可微映射在某一点的局部性质与其在该点的微分的性质相同”这一核心原理，我们可以猜测对于某一点 $P$，如果 $\det J\varphi(P)\neq 0$，对于 $P$ 附近的一个非常小的可求体积的图形 $A$，有 $\nu(\varphi(A)) = \lvert\det J\varphi(P)\rvert \nu(A)$. 对这样的一个个小的面
用 $p$，$P$ 容易被误认为矩阵

2024-08-23 15:05 UTC, 45gfg9 approved these changes

2024-08-23 15:47 UTC, FrightenedFoxCN commented on 讲义/专题/25 线性代数与微积分.tex
> +            &\mathbf{R}^{l}
```latex
\begin{tikzcd}
    & \mathbf{R}^m \arrow[rrr, "\mathrm{d} f"] \arrow[rrrdd, "\mathrm{d} (g \circ f)", swap] & & & \mathbf{R}^n \arrow[dd, "\mathrm{d} g"] \\
    D \arrow[rrr, "f", crossing over] \arrow[ru, dashed] \arrow[rrrdd, "g \circ f", swap] & & & E \arrow[dd, "g", crossing over] \arrow[ru, dashed] \\
    & & & & \mathbf{R}^l \\
    & & & U \arrow[ru, dashed]
\end{tikzcd}
```

2024-08-23 16:03 UTC, merged